list:
	rm -f list.cgi
	gcc -c -Wall list.c
	gcc -o list.cgi list.o

upload:
	rm -f upload.cgi
	gcc -c -Wall upload.c
	gcc -o upload.cgi upload.o

download:
	rm -f download.cgi
	gcc -c -Wall download.c
	gcc -o download.cgi download.o

remove:
	rm -f remove.cgi
	gcc -c -Wall remove.c
	gcc -o remove.cgi remove.o
